#!/bin/bash

# Retrieve the instance ID from the EC2 metadata service
INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)

# Print the instance ID
echo "The current instance ID is: $INSTANCE_ID"